PROG := ex02

COMPILER := g++
FLAGS := -Wall -Wextra -Werror
FLAGS_ALT := -std=c++98
SRCS =	main.cpp \
		ClapTrap.cpp \
		ScavTrap.cpp \
		FragTrap.cpp

OBJS := $(SRCS:.cpp=.o)

$(PROG): $(OBJS)
	$(COMPILER) $(FLAGS) -o $@ $(OBJS)

all: $(PROG)

clean:
	rm -f $(OBJS)

fclean:	clean
	rm -f $(PROG)

re:	fclean all

.PHONY:	all clean fclean re
